name: "Collect data"

on:
  schedule:
    - cron:  '30 12 * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        run: |
            pip install -r requirements.txt
            pip install -e .

      - name: Collect data
        run: python -m inflate.tools.scrape data/
        env:
          PRODUCTION: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: data
        path: data/

